Created a prototype of every enumerable method
RoyNyaga/ruby_enumerables pull request #2
Opened 2019-08-21 01:29 UTC by RoyNyaga

No comments

2019-08-21 01:50 UTC, RoyNyaga commented
I used the git flow concept and the library itself but did not make pull requests to merge to develop, once i finish with a feature branch, i merged to develop using the terminal command "git flow feature finish branch-name", it automatically merges the feature branch and deletes it.

2019-08-21 06:11 UTC, jofer86 requested changes
# :wave: :wave:  Hello!!! I'm Jorge and I'll be completing your code review today.
This was overall an excellent effort,  all of your code seems to be working like it should, with one exception though, please refer to the commented code to see what it is about.

Even though is a minor change I'm gonna have to ask you to resubmit for a code review, as the mistake I'm pointing is required to pass by the Microverse guidelines.

If you have any doubts contact me via Slack.

## Cheers, Jorge.

2019-08-21 06:11 UTC, jofer86 commented on enumerable.rb
> +  def my_count
This method works pretty well when a block is passed, however, we cannot pass an argument there si if I were to run the following code `[1,1,1].my_count(1)` it should return 3, but an error pops out. Please check that and make it work, once you are through with fixing that kindly resubmit.

2019-08-23 02:16 UTC, RoyNyaga commented
Fixed the bug in the my_count method as requested by the first reviewer. It can now take an argument without raising an error.

2019-08-23 10:18 UTC, bolah2009 approved these changes
## Awesome Job @RoyNyaga 

Good job implementing the changes suggested. :+1: 

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-23 14:22 UTC, RoyNyaga commented
Thanks sir,


On Fri, Aug 23, 2019 at 11:18 AM BOLA AHMED BUARI <notifications@github.com>
wrote:

> *@bolah2009* approved this pull request.
> Awesome Job @RoyNyaga <https://github.com/RoyNyaga>
>
> Good job implementing the changes suggested. 👍
>
> Good luck with your next project. 🌟
>
> Cheers
> Bola <https://bolabuari.com/>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/RoyNyaga/ruby_enumerables/pull/2?email_source=notifications&email_token=ALZGFHKA44R3TPYK54V4VUTQF62QJA5CNFSM4IN7Q3C2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCCP632Q#pullrequestreview-278916586>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALZGFHK6CJLQEXTXT6YO6ETQF62QJANCNFSM4IN7Q3CQ>
> .
>

2019-08-25 07:02 UTC, merged